---
  - name: Gather vars
    include_vars:
      dir: 'vars'
      extensions: ['yml']

  - name: Update boot config
    blockinfile:
      path: /boot/config.txt
      marker: "##<!-- {mark} ANSIBLE MANAGED -->"
      block: |
        #DISPLAY AND ROTATION
        # Display orientation. Landscape = 0, Portrait = 1
        display_rotate=0
        # Use 24 bit colors
        framebuffer_depth=24
        # HDMI power, display and contol settings
        disable_overscan=1
        config_hdmi_boost=7
        hdmi_force_hotplug=1
        # Overscan to adjust to custom TV framebuffer_depth
        overscan_left={{ screen_overscan_left }}
        overscan_right={{ screen_overscan_right }}

  - name: Create application folder structure
    file:
      path: /home/pi/application/calendar/
      state: directory
      mode: 0755

  - name: Startup options
    blockinfile:
      path: /home/pi/.config/lxsession/LXDE-pi/autostart
      marker: "##<!-- {mark} ANSIBLE MANAGED -->"
      block: |
        #Screensaver options
        @xset s off
        @xset s noblank
        @xset -dpms
        @unclutter -idle 5 -root
        @/usr/bin/xdg-settings set default-web-browser chromium-browser.desktop
        #Chromium start
        @/home/pi/application/calendar/start_dak.sh

  - name: Disable Screensaver
    lineinfile:
      path: /home/pi/.config/lxsession/LXDE-pi/autostart
      state: absent
      line: "@xscreensaver -no-splash"

  - name: Create startup script
    blockinfile:
      path: /home/pi/application/calendar/start_dak.sh
      marker: "##<!-- {mark} ANSIBLE MANAGED -->"
      block: |
        # Run browser after boot to desktop
        /bin/sleep 3
        DISPLAY=:0 chromium-browser --noerrdialogs --incognito --kiosk {{ dak_url }} &
        # End of script
      create: yes
      owner: root
      mode: 0777

  - name: Copy display control script
    copy:
      src: ../scripts/rpi-hdmi.sh
      dest: /home/pi/application/calendar/rpi-hdmi.sh
      owner: root
      mode: 0777

  - name: Set chromium as default browser
    shell: "xdg-settings set default-web-browser chromium-browser.desktop"
